### ISSUE TITLE
CreatePatch consumes lot of time while comparing two large JSON documents

### ISSUE THREAD

**Issue by anilkumarpodugu** [appscode/jsonpatch#27]
We have a large configuration in a JSON document (around 1000 elements in a list) and trying to remove the last element from the list. 
The CreatePatch() function is taking around 40 seconds to create a JSON patch.
This is effecting our characteristics.
We have tried the older versions (github.com/appscode/jsonpatch), the CreatePatch() is taking one second to create a JSON patch.
Please could you look into it.

**Comment by tamalsaha** [comment]
Sorry for the late response.

We are using edit-distance alg to determine optimal diffs. https://github.com/gomodules/jsonpatch/blob/v2.1.0/v2/jsonpatch.go#L278

This is an O(n^2) alg. So, it can take time for json objects with lots of direct child elements. In those cases, just a simple replace will be fast but the patch will be suboptimal.
