### ISSUE TITLE
The patch results generated by v2 and v3 are different

### ISSUE THREAD

**Issue by weidacn** [appscode/jsonpatch#31]
# For v2

## Source json:{"supportedNssaiAvailabilityData":[
{"tai":{"plmnId":{"mcc":"450","mnc":"05"},"tac":"000001"},"supportedSnssaiList":[
{"sst":1,"sd":"abd001"},
{"sst":3,"sd":"abd001"},
{"sst":3},
{"sst":2,"sd":"ab2112"}
]}
]}
## Target json:{"supportedNssaiAvailabilityData":[
{"tai":{"plmnId":{"mcc":"450","mnc":"05"},"tac":"000001"},"supportedSnssaiList":[
{"sst":2,"sd":"ab2112"},
{"sst":1,"sd":"abd001"},
{"sst":2,"sd":"ab2112"},
{"sst":3,"sd":"abd001"},
{"sst":3}
]}
]}
## Patch result:
{remove /supportedNssaiAvailabilityData/0/supportedSnssaiList/3 <nil>}
{add /supportedNssaiAvailabilityData/0/supportedSnssaiList/1 map[sd:ab2112 sst:2]}
{add /supportedNssaiAvailabilityData/0/supportedSnssaiList/0 map[sd:ab2112 sst:2]}

# For v3
Source json:{"supportedNssaiAvailabilityData":[
{"tai":{"plmnId":{"mcc":"450","mnc":"05"},"tac":"000001"},"supportedSnssaiList":[
{"sst":1,"sd":"abd001"},
{"sst":3,"sd":"abd001"},
{"sst":3},
{"sst":2,"sd":"ab2112"}
]}
]}
## Target json:{"supportedNssaiAvailabilityData":[
{"tai":{"plmnId":{"mcc":"450","mnc":"05"},"tac":"000001"},"supportedSnssaiList":[
{"sst":2,"sd":"ab2112"},
{"sst":1,"sd":"abd001"},
{"sst":2,"sd":"ab2112"},
{"sst":3,"sd":"abd001"},
{"sst":3}
]}
]}
## Patch result:
{add /supportedNssaiAvailabilityData/0/supportedSnssaiList/4 0xc0000ad700}
{replace /supportedNssaiAvailabilityData/0/supportedSnssaiList/0/sst 2}
{replace /supportedNssaiAvailabilityData/0/supportedSnssaiList/0/sd ab2112}
{replace /supportedNssaiAvailabilityData/0/supportedSnssaiList/1/sst 1}
{replace /supportedNssaiAvailabilityData/0/supportedSnssaiList/2/sst 2}
{add /supportedNssaiAvailabilityData/0/supportedSnssaiList/2/sd ab2112}
{replace /supportedNssaiAvailabilityData/0/supportedSnssaiList/3/sst 3}
{replace /supportedNssaiAvailabilityData/0/supportedSnssaiList/3/sd abd001}

It seems v2 is more efficient.

**Comment by tamalsaha** [comment]
v3 maintains original order of properties in a json object. So, it could produce less optimal patch. Use v3 if you are saving these patches in a git repo or such that you manually modify.

v2 and v3 both will product valid patches but v3 is preferred if the patches are going to be manually manipulated.
