### ISSUE TITLE
High Memory usage for CreatePatch function

### ISSUE THREAD

**Issue by akhilsharmanittala** [appscode/jsonpatch#35]
Create patch is consuming huge memory for the patch mentioned in uploaded file(create1.go.zip), we could observe initially memory is 0MB and after execution of createpatch function we observe memory is at 332MB. As the patch is small still we could see memory usage is high so is there any possibility to optimize memory usage.

[create1.go.zip](https://github.com/gomodules/jsonpatch/files/7362670/create1.go.zip)

**Comment by akhilsharmanittala** [comment]
Hi,

it would be helpful for us if there is some inputs regarding the above mentioned issue.

**Comment by howardjohn** [comment]
https://github.com/gomodules/jsonpatch/pull/36 plausibly fixes this

**Comment by tamalsaha** [comment]
Fixed, I think!
